######################################################################
# Automatically generated by qmake (1.03a) Wed Nov 29 10:31:20 2006
######################################################################

TEMPLATE = app

# Input
HEADERS += gameborad.h mine.h
SOURCES += gameborad.cpp main.cpp mine.cpp
